package recipes.view;

import recipes.controller.RecipeController;
import java.util.Observable;
import java.util.Observer;
import recipes.model.Recipe;
import recipes.model.Update;
import java.util.List;

public class RecipeView extends javax.swing.JFrame implements IView, Observer {
    
    private RecipeController controller;
    
    public RecipeView( RecipeController c, Observable o ) {

        controller = c; 
        o.addObserver( this );
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        mainIngredientLabel = new javax.swing.JLabel();
        preparationTimeLabel = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        preparationTimeTextField2 = new javax.swing.JTextField();
        mainIngredientTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        inputLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        outputLabel = new javax.swing.JLabel();
        cookingTimeLabel = new javax.swing.JLabel();
        preparationTimeTextField1 = new javax.swing.JTextField();
        cookingTimeTextField1 = new javax.swing.JTextField();
        cookingTimeTextField2 = new javax.swing.JTextField();
        queryLabel = new javax.swing.JLabel();
        CombinedCookingTimeLabel = new javax.swing.JLabel();
        combinedTimeTextField1 = new javax.swing.JTextField();
        combinedTimeTextField2 = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        categoryAndPreparationTimeButton = new javax.swing.JButton();
        categoryButton = new javax.swing.JButton();
        categoryAndCobinedTimeButton = new javax.swing.JButton();
        mainIngredientButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Booking System");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        categoryLabel.setText("Category");

        mainIngredientLabel.setText("Main Ingredient");

        preparationTimeLabel.setText("Preparation Time");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        inputLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inputLabel.setText("Input");

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        outputLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        outputLabel.setText("Output");

        cookingTimeLabel.setText("Cooking Time");

        queryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        queryLabel.setText("Select recipes for the following attributes:");

        CombinedCookingTimeLabel.setText("Combined Time");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        categoryAndPreparationTimeButton.setText("Category and Preparation Time");
        categoryAndPreparationTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAndPreparationTimeButtonActionPerformed(evt);
            }
        });

        categoryButton.setText("Category");
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });

        categoryAndCobinedTimeButton.setText("Category and Combined Time");
        categoryAndCobinedTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAndCobinedTimeButtonActionPerformed(evt);
            }
        });

        mainIngredientButton.setText("Main Ingredient");
        mainIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryButton)
                    .addComponent(categoryAndPreparationTimeButton)
                    .addComponent(categoryAndCobinedTimeButton)
                    .addComponent(mainIngredientButton))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryButton)
                .addGap(18, 18, 18)
                .addComponent(categoryAndPreparationTimeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryAndCobinedTimeButton)
                .addGap(18, 18, 18)
                .addComponent(mainIngredientButton)
                .addContainerGap())
        );

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(mainIngredientLabel)
                            .addComponent(preparationTimeLabel)
                            .addComponent(cookingTimeLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nameLabel)
                                .addComponent(inputLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cookingTimeTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(preparationTimeTextField1))
                                    .addComponent(combinedTimeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(preparationTimeTextField2)
                                    .addComponent(cookingTimeTextField2)
                                    .addComponent(mainIngredientTextField)
                                    .addComponent(combinedTimeTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(queryLabel)
                                    .addComponent(CombinedCookingTimeLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outputLabel)
                                .addGap(182, 182, 182))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(nextButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton)))
                    .addComponent(previousButton))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputLabel)
                    .addComponent(inputLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(preparationTimeLabel)
                                .addComponent(preparationTimeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(preparationTimeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cookingTimeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cookingTimeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cookingTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CombinedCookingTimeLabel)
                            .addComponent(combinedTimeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combinedTimeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mainIngredientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainIngredientLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(queryLabel)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(clearButton))
                        .addGap(67, 67, 67)
                        .addComponent(previousButton)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitButton)
                            .addComponent(nextButton))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        controller.close();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        String ctf = categoryTextField.getText();   
        if ( ctf.equals( "" ) ) {
            outputTextArea.setText( "No category entered\n" ); 
            return;
        }
        controller.recipesForCategory( ctf );
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String ntf = nameTextField.getText();
        String ctf = categoryTextField.getText();
        String mitf = mainIngredientTextField.getText();
        String pttf = preparationTimeTextField1.getText();
        String cttf = cookingTimeTextField1.getText();                                
        if (    ntf.equals( "" ) || 
                ctf.equals( "" ) ||
                mitf.equals( "" ) ||
                pttf.equals( "" ) ||
                cttf.equals( "" )
            ) {
            outputTextArea.setText( "All database fields must be specified\n" ); 
            return;            
        }
        
        int pt = Integer.parseInt( pttf );
        int ct = Integer.parseInt( cttf );

        controller.addRecipe( ntf, ctf, mitf, pt, ct );         
    }//GEN-LAST:event_addButtonActionPerformed

    private void categoryAndPreparationTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAndPreparationTimeButtonActionPerformed
        String ctf = categoryTextField.getText();
        String pttf1 = preparationTimeTextField1.getText();
        String pttf2 = preparationTimeTextField2.getText();
        if (ctf.equals( "" ) ) {
            outputTextArea.setText( "No category specified\n" ); 
            return;  
        }        
        int t[] = getTimes( pttf1, pttf2 );
        if ( t == null )
            return;       
        controller.recipesForCategoryAndPreparationTime( ctf, t[0], t[1] );
    }//GEN-LAST:event_categoryAndPreparationTimeButtonActionPerformed

    private void mainIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainIngredientButtonActionPerformed
        String mitf = mainIngredientTextField.getText();
        if (mitf.equals( "" ) ) {
            outputTextArea.setText( "No main ingredient specified\n" ); 
            return;  
        }   
        controller.numberOfRecipesUsingMainIngredient( mitf );
    }//GEN-LAST:event_mainIngredientButtonActionPerformed

    private void categoryAndCobinedTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAndCobinedTimeButtonActionPerformed
        String ctf = categoryTextField.getText();
        String cttf1 = combinedTimeTextField1.getText();
        String cttf2 = combinedTimeTextField2.getText();
        if (ctf.equals( "" ) ) {
            outputTextArea.setText( "No category specified\n" ); 
            return;  
        }
        int t[] = getTimes( cttf1, cttf2 );
        if ( t == null )
            return;    
        controller.recipesForCategoryAndCombinedTime( ctf, t[0], t[1] );
    }//GEN-LAST:event_categoryAndCobinedTimeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();                                                            
    }//GEN-LAST:event_clearButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        controller.previous();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        controller.next();
    }//GEN-LAST:event_nextButtonActionPerformed

    private int[] getTimes( String tf1, String tf2) {      
        int t[] = new int[2];
        if ( tf1.equals( "" ) && tf2.equals( "" ) ) {
           // should throw an exception
           outputTextArea.setText( "No values specified" ); 
          return null;
        }
        if ( tf1.equals( "" ))
            tf1 = "0";
        if ( tf2.equals( "" ))
           tf2 = tf1;     
        t[0] = Integer.parseInt( tf1);
        t[1] = Integer.parseInt( tf2 );
        if ( t[0] > t[1] ) {
           // should throw an exception
           outputTextArea.setText( "left value must be <= right value " ); 
          return null;
        }
        return t;
    }
    
    private void clear() {
        outputTextArea.setText( "" );
        nameTextField.setText( "" );
        categoryTextField.setText( "" );
        preparationTimeTextField1.setText( "" );
        preparationTimeTextField2.setText( "" );
        cookingTimeTextField1.setText( "" );
        cookingTimeTextField2.setText( "" );
        combinedTimeTextField1.setText( "" );
        combinedTimeTextField2.setText( "" );
        mainIngredientTextField.setText( "" );   
    }
    
    // IView implementation
    @Override
    public void setBrowsing( boolean flag ) {
        previousButton.setEnabled( flag );
        nextButton.setEnabled( flag );
    }
    
    @Override
    public void displayMessage( String s ) {
        outputTextArea.setText( s );  
    }
    
    @Override
    public void displayRecord( Recipe r ) {
        nameTextField.setText( r.getName() );
        categoryTextField.setText( r.getCategory() );
        preparationTimeTextField1.setText( Integer.toString( r.getPreparationTime() ) );
        preparationTimeTextField2.setText( "" );
        cookingTimeTextField1.setText( Integer.toString(r.getCookingTime() ) );
        cookingTimeTextField2.setText( "" );
        combinedTimeTextField1.setText( "" );
        combinedTimeTextField2.setText( "" );
        mainIngredientTextField.setText( r.getMainIngredient() );     
    }
    
    // Observer implementation
    @Override
    public void update( Observable o, Object u ) {
        Update update = (Update) u;
        Recipe r = update.getRecipe();
        String m = update.getMessage();
        clear();
        if ( r != null )
            displayRecord( r );
        if (m != null )
            displayMessage( m ); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CombinedCookingTimeLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton categoryAndCobinedTimeButton;
    private javax.swing.JButton categoryAndPreparationTimeButton;
    private javax.swing.JButton categoryButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField combinedTimeTextField1;
    private javax.swing.JTextField combinedTimeTextField2;
    private javax.swing.JLabel cookingTimeLabel;
    private javax.swing.JTextField cookingTimeTextField1;
    private javax.swing.JTextField cookingTimeTextField2;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainIngredientButton;
    private javax.swing.JLabel mainIngredientLabel;
    private javax.swing.JTextField mainIngredientTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JLabel preparationTimeLabel;
    private javax.swing.JTextField preparationTimeTextField1;
    private javax.swing.JTextField preparationTimeTextField2;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel queryLabel;
    // End of variables declaration//GEN-END:variables
}
